spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://43.200.49.215/ohsoontaxi
    username: ohsoontaxi
    password: 20181549
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture
        dialect:
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.hibernate.sql: debug